name: Build Image
on:
  push:

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
      - name: Build containers
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          make minidocker docker
      
      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io/jas88
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push mini-container to GitHub Container Repository
        id: push-mini-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: smidocker
          tags: latest
          registry: ghcr.io/jas88

      - name: Push full stack container to GitHub Container Repository
        id: push-full-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: smifull
          tags: latest
          registry: ghcr.io/jas88
